services:
  app: &app-master
    build: ./
    image: mongraph-app
    container_name: mongraph-app
    ports:
      - 127.0.0.1:8000:5000
    stop_grace_period: 3s

  cron:
    <<: *app-master
    container_name: mongraph-cron
    ports: []
    user: root
    entrypoint: ["crond", "-f", "-d", "5"]

  valkey:
    image: valkey/valkey:9.0-alpine
    container_name: mongraph-valkey
    volumes:
      - valkey_data:/data
    command: valkey-server --save 60 1

volumes:
  valkey_data:
    driver: local
