services:
  app: &app-master
    build:
      context: ./
      args:
        USER_GID: ${DOCKER_GID:-109}  # gid of docker.sock
    image: mongraph-app
    container_name: mongraph-app
    ports:
      - 127.0.0.1:8000:5000
    stop_grace_period: 3s

  cron:
    <<: *app-master
    container_name: mongraph-cron
    ports: []
    user: root
    volumes:
      # (!) directly mount log files will be "broken" after any kind of logrotate. Better mount directory of log files
      - /temp/mongraph/:/mnt/host_temp:ro  # to calc free space of host
      - /var/log/syslog:/mnt/host_syslog:ro  # to search OOM in host's log
      - /var/run/docker.sock:/mnt/host_docker.sock:rw  # to get host's docker information
    entrypoint: ["crond", "-f", "-d", "5"]

  valkey:
    image: valkey/valkey:9.1-alpine
    container_name: mongraph-valkey
    volumes:
      - valkey_data:/data
    command: valkey-server --save 60 1

volumes:
  valkey_data:
    driver: local
