# based on docker-compose.yml

services:
  app:
    build: ./
    image: mongraph-app
    container_name: mongraph-app
    ports:
      - 127.0.0.1:8000:5000
    volumes:
      - ./:/app
    entrypoint: ["uvicorn", "--host", "0.0.0.0", "--port", "5000", "--reload", "--reload-delay", "1", "server:app"]

  cron:
    volumes:
      - ./config/crontab:/etc/crontabs/app-user
      - ./:/app
